ECSOPS-213: Update plugins to latest
osu-mist/jenkins-pluginator pull request #4
Opened 2018-08-21 16:44 UTC by ianbrown9475

2018-08-21 20:21 UTC, tsoliangwu0130 requested changes

2018-08-21 20:21 UTC, tsoliangwu0130 commented on download_plugins.py
> +import utils
How did you order the import commands now? Is there any reason to order like this?

2018-08-21 20:21 UTC, tsoliangwu0130 commented on download_plugins.py
> +                    )
I suggest using [f-string](https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals) (Literal String Interpolation) to format string in Python 3.6 or above. It should be able to make the code looks better :)

2018-08-21 22:34 UTC, ianbrown9475 commented on download_plugins.py
> +import utils
They were ordered using "optimize imports" in PyCharm. Pretty sure it follows pep 8 https://www.python.org/dev/peps/pep-0008/#imports specifically:
> Imports should be grouped in the following order:
> 1. Standard library imports.
> 2. Related third party imports.
> 3. Local application/library specific imports.
>
> You should put a blank line between each group of imports.

2018-08-21 22:37 UTC, ianbrown9475 commented on download_plugins.py
> +                    )
Oh neat. I was wondering if there was an easy way in python to just insert variables in a string and it looks like you can do that as well as a lot of other stuff with this method, nice.

2018-08-22 22:23 UTC, tsoliangwu0130 commented on download_plugins.py
> +import utils
Good to know, thanks.

2018-08-22 22:28 UTC, tsoliangwu0130 approved these changes

2018-08-22 23:07 UTC, merged